services:
  postgresql:
    container_name: postgresql
    image: postgres:15.4-bullseye
    restart: always

    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_ms_pagos
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"

    volumes:
      - ./_data:/var/lib/postgresql/data
      - postgres_data_pagos:/var/lib/postgresql/data

networks:
  mired:
    driver: bridge

volumes:
  postgres_data_pagos:
